#!/usr/bin/env bash

if [ $# -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Extract arguments
file_path="$1"
server_ip="$2"
username="$3"
key_path="$4"

# Disable strict host key checking (not recommended for production)
export SSH_OPTS="-o StrictHostKeyChecking=no"

# Transfer the file with scp
scp -i "$key_path" "$file_path" "$username@$server_ip:~/""

# Check for success
if [ $? -eq 0 ]; then
	echo "File transferred successfully!"
else
	echo "Error transferring file."
fi

# Reset SSH options
unset SSH_OPTS
