#!/bin/bash
# Install nginx

sudo apt-get update
sudo apt-get install nginx -y

sudo sed -i 's/^$server {$/\1\n    listen 80;/' /etc/nginx/sites-available/default

sudo kill -s HUP $(pgrep nginx)

echo "Hello World!" | sudo tee /var/www/html/index.html

exit 0
