#!/usr/bin/env bash
# Configures NGINX Server To Listen on port 80 for All Servers 

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
